{% set name = "jnbv" %}
{% set version = "2021.8.17.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/jnbv-{{ version }}.tar.gz
  sha256: f0af5587f279e8900ce45e3c271c75fb4e5c577edc74b7f4e40302a50aa6103e

build:
  number: 0
  noarch: python
  entry_points:
    - jnbv = jnbv.__main__:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - nbformat ==5.1.3
    - papermill ==2.3.3
    - python >=3.6

test:
  imports:
    - jnbv
  commands:
    - pip check
    - jnbv --help
  requires:
    - pip

about:
  home: https://gitlab.com/MAXIV-SCISW/JUPYTERHUB/jnbv
  summary: Validation of Jupyter notebooks and kernels
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jasonbrudvik
